// Code generated by ydbgen; DO NOT EDIT.

package main

import (
	"strconv"

	"github.com/yandex-cloud/ydb-go-sdk"
	"github.com/yandex-cloud/ydb-go-sdk/table"
)

var (
	_ = strconv.Itoa
	_ = ydb.StringValue
	_ = table.NewQueryParameters
)

func (p *Project) Scan(res *table.Result) (err error) {
	res.SeekItem("id")
	p.id = res.OUint64()

	res.SeekItem("name")
	p.name = res.OUTF8()

	res.SeekItem("description")
	p.description = res.OUTF8()

	res.SeekItem("creator")
	p.creator = res.OUint64()

	return res.Err()
}

func (p *Project) QueryParameters() *table.QueryParameters {
	var v0 ydb.Value
	{
		vp0 := ydb.OptionalValue(ydb.Uint64Value(p.id))
		v0 = vp0
	}
	var v1 ydb.Value
	{
		vp0 := ydb.OptionalValue(ydb.UTF8Value(p.name))
		v1 = vp0
	}
	var v2 ydb.Value
	{
		vp0 := ydb.OptionalValue(ydb.UTF8Value(p.description))
		v2 = vp0
	}
	var v3 ydb.Value
	{
		vp0 := ydb.OptionalValue(ydb.Uint64Value(p.creator))
		v3 = vp0
	}
	return table.NewQueryParameters(
		table.ValueParam("$id", v0),
		table.ValueParam("$name", v1),
		table.ValueParam("$description", v2),
		table.ValueParam("$creator", v3),
	)
}

func (p *Project) StructValue() ydb.Value {
	var v0 ydb.Value
	{
		var v1 ydb.Value
		{
			vp0 := ydb.OptionalValue(ydb.Uint64Value(p.id))
			v1 = vp0
		}
		var v2 ydb.Value
		{
			vp0 := ydb.OptionalValue(ydb.UTF8Value(p.name))
			v2 = vp0
		}
		var v3 ydb.Value
		{
			vp0 := ydb.OptionalValue(ydb.UTF8Value(p.description))
			v3 = vp0
		}
		var v4 ydb.Value
		{
			vp0 := ydb.OptionalValue(ydb.Uint64Value(p.creator))
			v4 = vp0
		}
		v0 = ydb.StructValue(
			ydb.StructFieldValue("id", v1),
			ydb.StructFieldValue("name", v2),
			ydb.StructFieldValue("description", v3),
			ydb.StructFieldValue("creator", v4),
		)
	}
	return v0
}

func (p *Project) StructType() ydb.Type {
	var t0 ydb.Type
	{
		fs0 := make([]ydb.StructOption, 4)
		var t1 ydb.Type
		{
			tp0 := ydb.TypeUint64
			t1 = ydb.Optional(tp0)
		}
		fs0[0] = ydb.StructField("id", t1)
		var t2 ydb.Type
		{
			tp0 := ydb.TypeUTF8
			t2 = ydb.Optional(tp0)
		}
		fs0[1] = ydb.StructField("name", t2)
		var t3 ydb.Type
		{
			tp0 := ydb.TypeUTF8
			t3 = ydb.Optional(tp0)
		}
		fs0[2] = ydb.StructField("description", t3)
		var t4 ydb.Type
		{
			tp0 := ydb.TypeUint64
			t4 = ydb.Optional(tp0)
		}
		fs0[3] = ydb.StructField("creator", t4)
		t0 = ydb.Struct(fs0...)
	}
	return t0
}

func (ps *Projects) Scan(res *table.Result) (err error) {
	for res.NextRow() {
		var x0 Project
		res.SeekItem("id")
		x0.id = res.OUint64()

		res.SeekItem("name")
		x0.name = res.OUTF8()

		res.SeekItem("description")
		x0.description = res.OUTF8()

		res.SeekItem("creator")
		x0.creator = res.OUint64()

		if res.Err() == nil {
			*ps = append(*ps, x0)
		}
	}
	return res.Err()
}

func (ps Projects) ListValue() ydb.Value {
	var list0 ydb.Value
	vs0 := make([]ydb.Value, len(ps))
	for i0, item0 := range ps {
		var v0 ydb.Value
		{
			var v1 ydb.Value
			{
				var v2 ydb.Value
				{
					vp0 := ydb.OptionalValue(ydb.Uint64Value(item0.id))
					v2 = vp0
				}
				var v3 ydb.Value
				{
					vp0 := ydb.OptionalValue(ydb.UTF8Value(item0.name))
					v3 = vp0
				}
				var v4 ydb.Value
				{
					vp0 := ydb.OptionalValue(ydb.UTF8Value(item0.description))
					v4 = vp0
				}
				var v5 ydb.Value
				{
					vp0 := ydb.OptionalValue(ydb.Uint64Value(item0.creator))
					v5 = vp0
				}
				v1 = ydb.StructValue(
					ydb.StructFieldValue("id", v2),
					ydb.StructFieldValue("name", v3),
					ydb.StructFieldValue("description", v4),
					ydb.StructFieldValue("creator", v5),
				)
			}
			v0 = v1
		}
		vs0[i0] = v0
	}
	if len(vs0) == 0 {
		var t1 ydb.Type
		{
			var t2 ydb.Type
			{
				fs0 := make([]ydb.StructOption, 4)
				var t3 ydb.Type
				{
					tp0 := ydb.TypeUint64
					t3 = ydb.Optional(tp0)
				}
				fs0[0] = ydb.StructField("id", t3)
				var t4 ydb.Type
				{
					tp0 := ydb.TypeUTF8
					t4 = ydb.Optional(tp0)
				}
				fs0[1] = ydb.StructField("name", t4)
				var t5 ydb.Type
				{
					tp0 := ydb.TypeUTF8
					t5 = ydb.Optional(tp0)
				}
				fs0[2] = ydb.StructField("description", t5)
				var t6 ydb.Type
				{
					tp0 := ydb.TypeUint64
					t6 = ydb.Optional(tp0)
				}
				fs0[3] = ydb.StructField("creator", t6)
				t2 = ydb.Struct(fs0...)
			}
			t1 = t2
		}
		t0 := ydb.List(t1)
		list0 = ydb.ZeroValue(t0)
	} else {
		list0 = ydb.ListValue(vs0...)
	}
	return list0
}
